[versions]
kotlin-gradle-plugin = "1.9.20"
junit = "5.10.0"

[libraries]
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-gradle-plugin" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }